### ISSUE TITLE
ckpt for libero

### ISSUE THREAD

**Issue by yfpeng1234** [aiming-lab/GRAPE#1]
Dear author,
Thanks for the interesting work. Could you release the 4 ckpt in LIBERO?
Best

**Comment by zzj1111** [comment]
Thanks for reaching out!
We are not planning to release the LIBERO models and datasets we used in the paper experiments because of the limited storage capacity on the server, but I encourage you to collect dataset and train LIBERO models using our code by yourself. I will be glad to help you when you use our code.
Best
