### ISSUE TITLE
dataset for libero

### ISSUE THREAD

**Issue by zhan72** [aiming-lab/GRAPE#3]
Thanks for your wonderful work!
Do you have the DPO dataset collected in libero? I don't find it in the github.
Thanks!

**Comment by zzj1111** [comment]
Thanks for reaching out!
We are not planning to release the LIBERO models and datasets we used in the paper experiments because of the limited storage capacity on the server, but I encourage you to collect dataset and train LIBERO models using our code by yourself. I will be glad to help you when you use our code.
Moreover, we will release scripts for dataset construction soon. These may be helpful to you.
Best
